Import get_terminal_size from shutil
`get_terminal_size`  function has been removed from Click 8.1.0. We should use shutil.get_terminal_size instead.

This change is required to handle the following error when using Spacy 3.2.3.

```
ImportError: cannot import name 'get_terminal_size' from 'click.termui'
```