Bump `click` minimum version to 8.0.0
Click major version 7 does not properly work because of the following error:
`AttributeError: module 'click.utils' has no attribute '_expand_args'`

The `_expand_args` method was added in click major version 8.